# Generated by Django 4.1.5 on 2023-02-07 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0003_alter_seller_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='mobile',
            field=models.PositiveBigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='seller',
            name='mobile',
            field=models.PositiveIntegerField(),
        ),
    ]
