# Generated by Django 4.1.5 on 2023-02-07 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0004_contact_mobile_alter_seller_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='mobile',
            field=models.PositiveBigIntegerField(default=1),
            preserve_default=False,
        ),
    ]
